name: "image-processing-app"
services:

  postgresql_db:
    image: postgres:alpine3.19
    restart: always
    container_name: app-postgres
    volumes:
      - db-data:/var/lib/postgresql
    networks: # Port 5432
      - common-network
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DB_NAME}"]
      interval: 30s
      timeout: 60s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5 # 23.0.X and 24.0.X has problem with hibernate connection to database
    container_name: app-keycloak
    restart: always
    command: "start-dev --db=postgres --db-url=jdbc:postgresql://postgresql_db:5432/${DB_NAME} --db-username=${DB_USER} --db-password=${DB_PASSWORD} --import-realm"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    networks: # port 8443
      - common-network
    ports:        # For development purpose
      - "8443:8443"
      - "8080:8080"
    volumes:
      - ./AppComponents/Keycloak/ImageProcessor-realm.json:/opt/keycloak/data/import/realm.json
    depends_on:
      postgresql_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8443" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  common-network:

# sudo DB_PASSWORD=test1234 DB_USER=user DB_NAME=imageprocessor KEYCLOAK_ADMIN=admin KEYCLOAK_ADMIN_PASSWORD=admin docker compose up
# Keycloak ADMIN = admin:admin  USER = user:user
